services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
