services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv-jd-parser-backend
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cv-jd-parser-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: cv-jd-parser-redis
    ports:
      - "6379:6379"
