services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv-backend
    depends_on:
      - redis
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

